# Use an official Node.js runtime with Alpine Linux as the parent image
FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN cp .env.dev .env

# Expose the port your application will listen on (if applicable)
EXPOSE 8083

# Start your Node.js application
CMD ["npm", "start"]
